version: '3.3'

services:
  db:
    container_name: geek_shopping_product_api_db
    image: mysql
    environment:
      MYSQL_DATABASE: geek_shopping_product_api
      MYSQL_ROOT_PASSWORD: geek_shopping_product_api
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql/product:/var/lib/mysql