version: '3.3'

services:
  dbProductApi:
    container_name: geek_shopping_product_api_db
    image: mysql
    environment:
      MYSQL_DATABASE: geek_shopping_product_api
      MYSQL_ROOT_PASSWORD: geek_shopping_product_api
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./databases/mysql/product:/var/lib/mysql
  dbCartApi:
    container_name: geek_shopping_cart_api_db
    image: mysql
    environment:
      MYSQL_DATABASE: geek_shopping_cart_api
      MYSQL_ROOT_PASSWORD: geek_shopping_cart_api
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./databases/mysql/cart:/var/lib/mysql
  dbCouponApi:
    container_name: geek_shopping_coupon_api_db
    image: mysql
    environment:
      MYSQL_DATABASE: geek_shopping_coupon_api
      MYSQL_ROOT_PASSWORD: geek_shopping_coupon_api
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./databases/mysql/coupon:/var/lib/mysql
  dbOrderApi:
    container_name: geek_shopping_order_api_db
    image: mysql
    environment:
      MYSQL_DATABASE: geek_shopping_order_api
      MYSQL_ROOT_PASSWORD: geek_shopping_order_api
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - ./databases/mysql/order:/var/lib/mysql
  rabbitmq:
    container_name: geek_shopping_rabbitmq
    image: rabbitmq:3-management
    ports:
        - 15672:15672
        - 5672:5672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/